export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function combiLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <h2>Presidential Initiative for Artificial Intelligence and Computing</h2>
      <hr></hr>
      {children}
    </div>

  );
}